[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Menambahkan bagian baru untuk mendaftarkan RPC Endpoint kita
[rpc_endpoints]
monad_testnet = "${MONAD_RPC_URL}"
